# Generated by Django 3.2.13 on 2022-05-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='name',
        ),
    ]
